DROP SCHEMA public CASCADE;
CREATE SCHEMA public;

GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO public;
GRANT ALL ON SCHEMA public TO acme_db;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO acme_db;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO acme_db;
