swagger: "2.0"

info:
  version: 1.0.0
  title:  mobile application API
  description: First Version Mobile API

schemes:
  - https
host: simple.api
basePath: /openapi101

paths:
  /deliveriesList:
    post:
      summary: Gets list of parcels for current D.O.
      parameters:
        - name: userToken
          in: body
          required: true
          description: Uniquie authorization token for User
          type: string 
      responses:
        200:
          description: A list of Parcels assigned to driver returned
          schema:
            $ref: '#/definitions/Parcels'
        400:
          description: The list of parcels for this driver wasn't found
          schema:
            $ref: '#/definitions/ErrorResponse'
  /deliveriesInProgress:
    post:
      summary: Gets list of parcels in progress for current D.O.
      parameters:
        - name: userToken
          required: true
          in: body
          description: Uniquie authorization token for User
          type: string 
      responses:
        200:
          description: A list of Parcels in progress assigned to driver returned
          schema:
            $ref: '#/definitions/Parcels'
        400:
          description: The list of parcels for this driver wasn't found
          schema:
            $ref: '#/definitions/ErrorResponse'
  /auth:
    post:
      summary: Authorization
      parameters:
        - name: username
          in: body
          required: true
          description: User uniquie username
          type: string
        - name: password
          required: true
          in: body
          description: password
          type: string
      responses:
        200:
          description: Succesful Login
          schema:
            $ref: "#/definitions/Token"
        400:
          description: Incorrect login or password
          schema:
            $ref: "#/definitions/ErrorResponse"
  /logout:
    post:
      summary: Log out
      parameters: 
        - name: Token
          required: true
          in: body
          description: Unique Token for user
          type: string
      responses:
        200:
          description: Succesful Log out
        400:
          description:  User is already logged out
          schema:
            $ref: "#/definitions/ErrorResponse"
            
  /checkToken:
    post:
      summary: Check is the token valid
      parameters: 
        - name: Token
          required: true
          in: body
          description: Unique Token  for user
          schema:
            $ref: "#/definitions/Token"
      responses:
        200:
          description: Token Status returned
          schema:
            $ref: "#/definitions/TokenValidationResponse"
        400:
          description:  Wrong Token Input
          schema:
            $ref: "#/definitions/ErrorResponse"


  /changeParcelStatus:
    post:
      summary: Change parcel status
      parameters: 
        - name: Token
          required: true
          in: body
          description: ID Unique for parcel
          type: string
        - name: ParcelStatus 
          required: true
          in: body
          description: Status from Enum
          schema:
            enum: [delivered, in progress,assigned,waited]
      responses:
        200:
          description: Parcel status was succesfully changed
        400:
          description:  Wrong Parcel ID or Status Input
  


definitions:
  Parcel:
    required:
      - parcelID
      - deliveryTime
      - address
      - contact
      - mapsCoordinate
    properties:
      parcelID:
        type: string
      deliveryTime:
        type: string
        format: date-time #TODO: Keep it in date-time format or make it just string?
      address:
        type: string
      contact:
        type: string
      mapsCoordinates:
        type: string
  Parcels:
    type: array
    items:
      $ref: '#/definitions/Parcel'
  Token:
    required:
      - tokenString
    properties:
      tokenString:
        description: unique token for user
        type: string
  ErrorResponse:
    required:
      - errorCode
    properties:
      errorCode:
        type: integer
      description:
        type: string
  TokenValidationResponse:
    required:
      - tokenStatus
    properties:
      tokenStatus:
        type: string #valid or not
      description:
        type: string
  