# Generated by Django 2.1.2 on 2018-11-07 09:59

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import web_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcmeCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AcmeOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField()),
                ('comment', models.TextField()),
                ('priority', models.IntegerField()),
                ('scheduled_time', web_app.models.DeliveryPeriod()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web_app.AcmeCustomer')),
            ],
        ),
        migrations.CreateModel(
            name='AcmeOrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField()),
                ('status', models.CharField(choices=[(web_app.models.OrderStatusType('created'), 'created'), (web_app.models.OrderStatusType('approved'), 'approved'), (web_app.models.OrderStatusType('en_route'), 'en_route'), (web_app.models.OrderStatusType('stored'), 'stored'), (web_app.models.OrderStatusType('delivered'), 'delivered')], max_length=20)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web_app.AcmeOrder')),
            ],
        ),
        migrations.CreateModel(
            name='AcmeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=16)),
                ('user_location', models.CharField(choices=[(web_app.models.AcmeLocations('EU'), 'EU'), (web_app.models.AcmeLocations('RU'), 'RU'), (web_app.models.AcmeLocations('CH'), 'CH'), (web_app.models.AcmeLocations('UK'), 'UK')], max_length=5)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('file_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('additional_info', models.TextField()),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_address', models.CharField(max_length=255)),
                ('lat_long', web_app.models.Coordinates()),
            ],
        ),
        migrations.CreateModel(
            name='OrderDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_status', models.CharField(choices=[(web_app.models.DeliveryStatusTypes('pending'), 'pending'), (web_app.models.DeliveryStatusTypes('in_progress'), 'in_progress'), (web_app.models.DeliveryStatusTypes('completed'), 'completed')], max_length=20)),
                ('active_time_period', django.contrib.postgres.fields.ArrayField(base_field=web_app.models.DeliveryPeriod(), size=None)),
                ('end_location_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_delivery_end_location', to='web_app.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('dimension', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=3)),
                ('shape', models.CharField(choices=[(web_app.models.ShapeTypes('postcard'), 'postcard'), (web_app.models.ShapeTypes('letter'), 'letter'), (web_app.models.ShapeTypes('large_envelope'), 'large_envelope'), (web_app.models.ShapeTypes('parcel'), 'parcel')], max_length=20)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.AcmeOrder')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[(web_app.models.AcmeRoles('CEO'), 'CEO'), (web_app.models.AcmeRoles('DO'), 'DO'), (web_app.models.AcmeRoles('CO'), 'CO'), (web_app.models.AcmeRoles('CS'), 'CS'), (web_app.models.AcmeRoles('CD'), 'CD')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_name', models.CharField(max_length=255)),
                ('max_capacity', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web_app.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryOperator',
            fields=[
                ('operator_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='web_app.AcmeUser')),
                ('pos_last_updated', models.DateTimeField(null=True)),
                ('current_pos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web_app.Location')),
            ],
        ),
        migrations.AddField(
            model_name='userrole',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web_app.AcmeUser'),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.AcmeUser'),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='start_location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_delivery_start_location', to='web_app.Location'),
        ),
        migrations.AddField(
            model_name='acmeuser',
            name='contact_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web_app.Contact'),
        ),
        migrations.AddField(
            model_name='acmeorderstatus',
            name='warehouse_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web_app.Warehouse'),
        ),
        migrations.AddField(
            model_name='acmeorder',
            name='end_location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acme_order_end_location', to='web_app.Location'),
        ),
        migrations.AddField(
            model_name='acmeorder',
            name='start_location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acme_order_start_location', to='web_app.Location'),
        ),
        migrations.AddField(
            model_name='acmecustomer',
            name='contact_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web_app.Contact'),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='delivery_operator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.DeliveryOperator'),
        ),
        migrations.AlterUniqueTogether(
            name='acmeorderstatus',
            unique_together={('order_id', 'created_on')},
        ),
        migrations.AlterUniqueTogether(
            name='orderdelivery',
            unique_together={('order_id', 'delivery_operator_id')},
        ),
    ]
