# Generated by Django 2.1.2 on 2018-11-13 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acmeorderstatus',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='acmeorderstatus',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_status', to='web_app.AcmeOrder'),
        ),
        migrations.AlterField(
            model_name='acmeorderstatus',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web_app.Warehouse'),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='delivery_operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_operator', to='web_app.DeliveryOperator'),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_deliveries', to='web_app.AcmeOrder'),
        ),
    ]
