# Generated by Django 2.1.3 on 2018-11-11 20:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acmeorder',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='acmeuser',
            name='avatar_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='additional_info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='position',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='active_time_period',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
