# Generated by Django 2.1.3 on 2018-11-12 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_auto_20181111_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acmeorderstatus',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_status', to='web_app.AcmeOrder'),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_deliveries', to='web_app.AcmeOrder'),
        ),
    ]
