# Generated by Django 2.1.2 on 2018-11-12 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_auto_20181111_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web_app.Location'),
        ),
    ]
