# Generated by Django 2.1.3 on 2018-11-12 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_auto_20181112_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acmeorderstatus',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_status', to='web_app.AcmeOrder'),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='delivery_operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_operator', to='web_app.DeliveryOperator'),
        ),
    ]
