# Generated by Django 2.1.3 on 2018-11-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_auto_20181112_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acmeorderstatus',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
