# Generated by Django 2.1.3 on 2018-11-12 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0005_auto_20181112_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acmeorderstatus',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web_app.Warehouse'),
        ),
    ]
